# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.56.101"

    if Vagrant.has_plugin?("vagrant-vbguest")
      web.vbguest.auto_update = false
    end

    web.vm.provision "shell", path: ".scripts/initial_web.sh"
    web.vm.provision "shell", path: "web.sh"
  
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/bionic64"
    db.vm.hostname = "db"  
    db.vm.network "private_network", ip: "192.168.56.102"

    if Vagrant.has_plugin?("vagrant-vbguest")
      db.vbguest.auto_update = false
    end

    db.vm.provision "shell", path: ".scripts/initial_db.sh"
    db.vm.provision "shell", path: "db.sh"

  end 
    
end
