Vagrant.configure("2") do |config|

  config.vm.define "vm1" do |vm|
    vm.vm.box = "ubuntu/jammy64"
    vm.vm.hostname = "vm1"
    vm.vm.network "private_network", ip: "192.168.56.103"

    if Vagrant.has_plugin?("vagrant-vbguest")
      vm.vbguest.auto_update = false
    end

    vm.vm.provision "shell", path: ".scripts/initial_vm1.sh"
    vm.vm.provision "shell", path: "vm1.sh"
  
  end

  config.vm.define "vm2" do |vm|
    vm.vm.box = "ubuntu/jammy64"
    vm.vm.hostname = "vm2"  
    vm.vm.network "private_network", ip: "192.168.56.104"

    if Vagrant.has_plugin?("vagrant-vbguest")
      vm.vbguest.auto_update = false
    end

    vm.vm.provision "shell", path: ".scripts/initial_vm2.sh"
    vm.vm.provision "shell", path: "vm2.sh"

  end 
    
end
