Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "TareaVagrant"
    config.vm.network 'private_network', ip: "192.168.56.201"

    config.vm.provision "shell", path: "install-apache2.sh"
    config.vm.provision "shell", path: "configure-fail2ban.sh"
  end